[build]
  command = "npm install @octokit/rest marked js-yaml sanitize-html && node netlify/functions/generate-files.cjs"
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
  force = true
  headers = { "Content-Type" = "application/xml" }

[context.production.environment]
  NODE_VERSION = "16"
  GITHUB_TOKEN = "{{GITHUB_TOKEN}}"
  GITHUB_OWNER = "{{GITHUB_OWNER}}"
  GITHUB_REPO = "{{GITHUB_REPO}}"
  ADMIN_PASSWORD = "{{ADMIN_PASSWORD}}"
  NETLIFY_BUILD_HOOK = "{{NETLIFY_BUILD_HOOK}}"