[build]
  command = "npm run build" # Adjust for your build process
  publish = "dist" # Adjust to your output directory
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200