[build]
  command = "echo 'No build needed'"
  publish = "."
  functions = "functions"  # Only if using Netlify Functions

[build.environment]
  GITHUB_REPO = "DKTJONATHAN/Portfolio"
  NODE_VERSION = "18"  # Updated to 18 for compatibility

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "nft"