[build]
  publish = "."
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"  # Explicit npm version
  GITHUB_REPO = "DKTJONATHAN/portfolio"
  GITHUB_BRANCH = "main"
  # Never put tokens here - set in Netlify UI:
  # GITHUB_TOKEN, GITHUB_OWNER, GITHUB_PATH

[functions]
  node_bundler = "esbuild"
  included_files = []  # Remove if not using JSON data files
  # Add if using large modules:
  external_node_modules = ["@octokit/core"]

# Improved redirects for SPAs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Ensures rewrite even if file exists

# Enhanced security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
