[build]
  command = "echo 'No build needed'"
  publish = "."
  functions = "functions"

[build.environment]
  NETLIFY_CMS = "true"
  NODE_VERSION = "18"

# Required redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CMS redirect - MUST COME BEFORE CATCH-ALL
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Blog redirects
[[redirects]]
  from = "/blogs/posts/*"
  to = "/blogs/:slug"
  status = 200

[functions]
  node_bundler = "esbuild"
