[build]
  command = "" # No build command for plain HTML
  publish = "." # Use "." for root directory (more standard than "/")
  functions = "netlify/functions" # Functions directory

[[redirects]]
  from = "/api/list-posts"
  to = "/.netlify/functions/list-posts"
  status = 200

[[redirects]]
  from = "/api/storesubmission"
  to = "/.netlify/functions/storesubmission"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/static/admin/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200