[build]
  publish = "."
  functions = "functions"

# REQUIRED - Handles CMS routing
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Optional - For single-page apps
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
