backend:
  name: git-gateway
  branch: main # Use your repo’s default branch (e.g., main or master)
media_folder: "static/uploads" # Where images are stored
public_folder: "/uploads" # Public path for images
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog" # Where blog posts are saved
    create: true # Allow creating new posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename format
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }