backend:
  name: git-gateway
  branch: main # Your GitHub branch (replace with your branch name if different)
media_folder: "public/images/uploads" # Folder for uploaded images
public_folder: "/images/uploads" # Public path for images
collections:
  - name: "blog"
    label: "Blog"
    folder: "public/blog" # Folder where blog posts will be stored as Markdown
    create: true # Allow creating new posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md" # File name format
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }