backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"  # Where uploaded images are stored
public_folder: "/uploads"      # Public URL path

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home Page"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Content", widget: "markdown" }
