backend:
  name: git-gateway       # Netlify's authentication
  branch: main            # Your Git branch

# Store media (images) in a "static/uploads" folder
media_folder: "static/uploads"      # Folder where images go
public_folder: "/uploads"           # Public URL path

# Content collections (e.g., blog posts or pages)
collections:
  - name: "pages"                   # Generic pages (About, Home, etc.)
    label: "Pages"
    files:
      - file: "content/home.md"     # Homepage content
        label: "Home Page"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "hero_text", label: "Hero Text", widget: "text" }
          - { name: "body", label: "Content", widget: "markdown" }

      - file: "content/about.md"    # About page content
        label: "About Page"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "team", label: "Team Members", widget: "list", fields: [
              { name: "name", label: "Name", widget: "string" },
              { name: "role", label: "Role", widget: "string" }
            ] }
