backend:
  name: git-gateway
  branch: main # Your repository’s main branch
media_folder: "content/images" # Where images will be stored
public_folder: "/content/images" # Public path for images
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}.md" # Blog posts saved as Markdown files
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }