backend:
  name: github
  repo: DKTJONATHAN/portfolio  # Your repo
  branch: main                # Default branch
media_folder: "static/img/uploads"  # Where images are stored
public_folder: "/img/uploads"
collections:
  - name: "projects"          # Example: Manage portfolio projects
    label: "Projects"
    folder: "_projects"       # Your projects folder (create if missing)
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Cover Image", widget: "image" }
      - { name: "body", label: "Content", widget: "markdown" }